[package]
name = "lsd"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
owo-colors = { version = "4.2.1"}
chrono = { version = "0.4.41"}
tabled = "0.20.0"
strum = "0.27.1"
strum_macros = "0.27.1"
